let $DOTFILES_PATH = expand($HOME . "/Dropbox/dotfiles")
let $SHARED_VIMRC = expand($DOTFILES_PATH . "/vimrc")

if filereadable($SHARED_VIMRC)
  let $MYVIMRC = $SHARED_VIMRC
  exec ":source " . $SHARED_VIMRC
endif
